import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const base=process.env.TEST_URL||'http://127.0.0.1:3000';
const browser=await chromium.launch({channel:'msedge',headless:true});
const host=await browser.newContext({viewport:{width:1440,height:1100}});
const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
const errors=[];
const page=await host.newPage(),player=await mobile.newPage();
for(const p of [page,player])p.on('pageerror',e=>errors.push(e.message));
fs.mkdirSync('output/playwright',{recursive:true});
const screenshot=async(p,name)=>p.screenshot({path:`output/playwright/${name}.png`,fullPage:true,animations:'disabled'});
const overflow=async p=>assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'no horizontal overflow');
try {
 await page.goto(base);await page.getByRole('button',{name:/เปิดห้องกิจกรรม/}).waitFor();
 await screenshot(page,'home-desktop');await overflow(page);
 await player.goto(base);await player.getByRole('button',{name:/เปิดห้องกิจกรรม/}).waitFor();await screenshot(player,'home-mobile');await overflow(player);
 await page.getByRole('button',{name:/เปิดห้องกิจกรรม/}).click();await page.waitForURL(/host=/);
 const code=new URL(page.url()).searchParams.get('host');
 let loseFirstJoin=true;await player.route('**/api/rooms/*/join',async route=>{if(loseFirstJoin){loseFirstJoin=false;await route.fetch();await route.abort('failed')}else await route.continue()});
 await player.goto(`${base}/?join=${code}`);await player.getByLabel('รหัสพนักงาน',{exact:true}).fill('EMP0');await player.getByLabel('ชื่อเล่นที่เพื่อนจะเห็น').fill('มายด์');await player.getByRole('button',{name:/สุ่มทีมแล้วเข้าเล่น/}).click();
 await player.locator('#toast.visible').waitFor();await player.getByRole('button',{name:/สุ่มทีมแล้วเข้าเล่น/}).click();
 await player.getByRole('button',{name:'พร้อมลุยกับทีมนี้!'}).click();
 await player.getByText('คุณอยู่ทีม').waitFor({timeout:8000});
 const call=async(path,body,token)=>{const r=await fetch(base+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined});const data=await r.json();assert.equal(r.ok,true,JSON.stringify(data));return data};
 await page.locator('.network summary').click();
 await page.locator('#base-url').fill('http://192.168.1.123:3000');
 const others=[];for(let i=1;i<20;i++)others.push(await call(`/api/rooms/${code}/join`,{name:`เพื่อน ${i}`,employeeId:`EMP${i}`}));
 await page.waitForFunction(()=>document.querySelector('.lobby-stats b')?.textContent.startsWith('20'));
 assert.equal(await page.locator('#base-url').inputValue(),'http://192.168.1.123:3000','unsaved QR address survives new joins');
 assert.equal(await page.locator('.network').evaluate(el=>el.open),true,'network details remains open');
 await page.locator('.network summary').click();await page.getByLabel('เวลาตอบแต่ละข้อ').selectOption('30');await screenshot(page,'host-lobby');await screenshot(player,'player-lobby');
 const publicScreen=await host.newPage();publicScreen.on('pageerror',e=>errors.push(e.message));await publicScreen.goto(`${base}/?screen=${code}`);await publicScreen.getByText('รวมทีม เตรียมลุย!',{exact:true}).waitFor();assert.equal(await publicScreen.locator('[data-control]').count(),0);
 await page.getByRole('button',{name:/เริ่มภารกิจ/}).click();
 await page.locator('#intro-count').waitFor();await screenshot(page,'intro-countdown');
 await player.locator('[data-choice="1"]').waitFor();await screenshot(page,'live-question');await screenshot(player,'live-question-mobile');
 await page.getByRole('button',{name:'♪ เปิดเสียง',exact:true}).click();assert.equal(await page.getByRole('button',{name:'♪ ปิดเสียง',exact:true}).getAttribute('aria-pressed'),'true');
 const initialClock=await player.locator('#timer').innerText();await player.waitForFunction(prev=>document.querySelector('#timer')?.textContent!==prev,initialClock);assert.ok(Number(await player.locator('#timer').innerText())<Number(initialClock));
 await player.locator('[data-choice="1"]').click();await player.getByRole('button',{name:/ยืนยันคำตอบ B/}).click();await player.getByText('ส่งคำตอบ B แล้ว',{exact:false}).waitFor();
 await player.reload();await player.getByText('ส่งคำตอบ B แล้ว',{exact:false}).waitFor();
 const hostToken=await page.evaluate(c=>localStorage.getItem(`dg:host:${c}`),code);
 for(const p of others)await call(`/api/rooms/${code}/answer`,{q:0,choice:1},p.token);
 await page.getByRole('button',{name:/เปิดเฉลยและให้คะแนน/}).click();await player.getByText('+100 คะแนนให้ทีม',{exact:false}).waitFor();
 await screenshot(page,'host-reveal');await screenshot(player,'player-reveal');await overflow(player);
 await page.getByRole('button',{name:/ลุ้นอันดับทีม/}).click();await page.locator('.ranking-list').waitFor();await screenshot(page,'leaderboard');await player.locator('.ranking-list').waitFor();await screenshot(player,'leaderboard-mobile');await overflow(player);
 await page.getByRole('button',{name:/ไปข้อถัดไป/}).click();
 const answers=[1,2,0,3,2,1,0,3,1,3];
 const playerToken=await player.evaluate(c=>localStorage.getItem(`dg:player:${c}`),code);
 for(let q=1;q<10;q++){
  let current;do{current=await call(`/api/rooms/${code}`);if(current.phase==='countdown')await new Promise(resolve=>setTimeout(resolve,100))}while(current.phase==='countdown');
  for(const p of [{token:playerToken},...others])await call(`/api/rooms/${code}/answer`,{q,choice:answers[q]},p.token);
  await call(`/api/rooms/${code}/control`,{action:'reveal'},hostToken);
  await call(`/api/rooms/${code}/control`,{action:'leaderboard'},hostToken);
  await call(`/api/rooms/${code}/control`,{action:'next'},hostToken);
 }
 await page.getByText('ภารกิจสำเร็จ!',{exact:true}).waitFor();await screenshot(page,'winner');await overflow(page);
 await player.getByText('ภารกิจสำเร็จ!',{exact:true}).waitFor();await screenshot(player,'winner-mobile');await overflow(player);
 const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:/ดาวน์โหลดผล/}).click();const download=await downloadEvent;assert.match(download.suggestedFilename(),new RegExp(code));
 await page.getByRole('button',{name:/เปิดห้องสำหรับกลุ่มถัดไป/}).click();await page.waitForURL(url=>url.searchParams.get('host')!==code);assert.notEqual(new URL(page.url()).searchParams.get('host'),code);
 const final=await call(`/api/rooms/${code}`);assert.equal(final.total,10);assert.deepEqual(final.teams.map(t=>t.count).sort(),[6,7,7]);assert.ok(final.teams.every(t=>t.percent===100&&t.score===t.count*1200&&t.rank===1));assert.ok(final.players.every(p=>p.employeeId===undefined));
 await page.goto(base);await page.getByRole('button',{name:/ลองเล่นโหมดสาธิต/}).click();await page.waitForURL(/host=/);await page.getByRole('button',{name:/เริ่มภารกิจ/}).click();await page.getByRole('button',{name:/เปิดเฉลยและให้คะแนน/}).waitFor({timeout:12000});
 await screenshot(page,'demo-question');assert.deepEqual(errors,[]);
 console.log('PASS: employee sign-in with lost-response retry, team reveal, 20 players in 3 random balanced teams, 3-2-1, live timer, audio toggle, 10 questions, histogram, leaderboard, 7/7/6 fair ties, refresh, export, new room, demo, public screen, mobile layouts.');
} finally {await browser.close()}
